### ISSUE TITLE
Question in WebTelnet can't be answered on mobile browser

### ISSUE THREAD

**Issue by btittelbach** [realraum/telme10#1]
Hi,

on mobile browsers, a keyboard to enter Y/N does not appear.

Thus the important information like starttime, location, information links, never appears.

As possible fix, I propose to display two click/touchable buttons for [Y] and [N] next to the promt in a font like this:
http://www.fontspace.com/casady-and-greene/keycapsflf

**Comment by PeterTheOne** [comment]
No Y and N buttons but touch just confirms for now. Please deploy!

**Comment by btittelbach** [comment]
This solution tells me, you currently don't have much time at hand ;-)
Insofar it's sufficient and ok. thnx.

As far as UI design goes tough, I'm not sure everyone will

* know what to do
* know that something can be done
* know what happened or why if they touch accidentally ;->

Also I'd really would have liked the buttons for mouse users as well. Leet doesn't mean it can'be userfriendly.
